### PR TITLE
Upgrade babashka.fs to fix static build on windows

### LINKED ISSUE #141: `clerk/expand-paths` not working on windows
Thank you for creating clerk!

The static site generation fails in windows, tracking down the issue with martin resolved in finding this: 
```clojure
(clerk/expand-paths ["notebooks\\rule_30.clj"])
;; => []
```

Martin remarked:
"wondering if the `fs/glob` is a problem https://github.com/nextjournal/clerk/blob/main/src/nextjournal/clerk.clj#L457
[clerk.clj](https://github.com/nextjournal/clerk/blob/main/src/nextjournal/clerk.clj)"

### PR DESCRIPTION
**Pull request by borkdude**
Fixes #141.

### CODE REVIEW

**Comment by borkdude** [comment]
Perhaps we need an additional test for this?

**Comment by mk** [comment]
Yep, a test for expand-paths would be good. I didn’t want to write it without knowing if the implementation would normalize the fs separators.

**Comment by borkdude** [comment]
@mk Added a test and verified that the test fails with fs 0.1.4, but works with fs 0.1.5

**Comment by mk** [comment]
@borkdude excellent, thank you!

**Pull request merged**
