### PR TITLE
Read config values from ENV, Java properties and CLI args

### PR DESCRIPTION
**Pull request by Sohalt**
Some work towards unifying where configuration is read from.

Specifically this allows specifying the clerk cache location on the command line or with `exec-args`.

### CODE REVIEW

**Comment by mk** [comment]
You can specify Java props from the Clojure cli as well so I don’t understand what problem this solves. Can we start with that?

**Comment by Sohalt** [comment]
You can specify them on the clojure cli, when invoking it yourself, but not eg in `:exec-args` for use in garden or when calling clerk "as a library" from other clojure code.

**Comment by mk** [comment]
An alias can specify jvm opts which should cover the garden use case? When using clerk as a library you can set the JVM prop programmatically.

**Comment by jackrusher** [comment]
@mk The requirement to deal with both JVM opts and potential command line args come from me. Let's chat about it tomorrow.

**Comment by Sohalt** [comment]
I'm just writing to properties for now.

**Pull request closed without merging**
