### PR TITLE
Codemirror Server Side Rendering

### PR DESCRIPTION
**Pull request by zampino**
* fixes server-side rendering of code cells
* drops codemirror view instances in favour of parsing clojure code with lezer and adding syntax highlighting

### CODE REVIEW

**Comment by mk** [comment]
I _think_ there's still some issues with styling but the things I did notice that we're erroring on doc strings so e.g. `(def foo "bar" :baz)` will produce a white screen of death.

**Comment by zampino** [comment]
Docstring fixed in dae3ef7. There's still an issue with code _results_...

CleanShot 2022-11-14 at 10 38 19@2x

**Comment by zampino** [comment]
> I think there's still some issues with styling

There's some dynamic CSS styles (with generated "scopes") injected in <head/> by [codemirror theme](https://github.com/nextjournal/clerk/pull/275/commits/5ef2e0415bbca19e519845963a34eb1b66756c70#diff-cc47688828e6345582744b8a90a5b22ee617035b69c25d7861f47499ab386793L11-L31) extension which is pertaining to the interactive editor instance.

_main_
CleanShot 2022-11-14 at 11 06 05@2x

CleanShot 2022-11-14 at 11 01 55@2x

(e.g. https://snapshots.nextjournal.com/clerk/build/edd0c2fc22bd0207cc8d3762f00f239ce63ee87f/index.html)

_this branch_
CleanShot 2022-11-14 at 10 58 27@2x
(https://snapshots.nextjournal.com/clerk/build/97d61665adcd35f98de38752f0d8441cff0a6ae1/index.html)

We could manually re-add theme styles concerning font-size and line-height or just ignore it, the difference is barely visible.

**Comment by zampino** [comment]
[a4fbdb9](https://github.com/nextjournal/clerk/pull/275/commits/a4fbdb96e5b3a8bdde1ba382e71abc2084ad56f8) addresses both issues mentioned above. 

There still a little padding discrepancy that I don't know how to fix, this is coming from styles injected by codemirror: 
CleanShot 2022-11-14 at 12 00 32@2x
but I cannot put it on the `.cm-content` element style as it would be more specific than our notebook styles.

Compare 👾 Code section, on this branch: 

https://snapshots.nextjournal.com/clerk/build/a4fbdb96e5b3a8bdde1ba382e71abc2084ad56f8/index.html#/notebooks/viewer_api.clj 

with main:

https://snapshots.nextjournal.com/clerk/build/edd0c2fc22bd0207cc8d3762f00f239ce63ee87f/index.html#/notebooks/viewer_api.clj

**Comment by zampino** [comment]
I'm getting this error on `bb dev`

```
shadow-cljs - server version: 2.20.10 running at http://localhost:9631
[:viewer] Configuring build.
[:viewer] Compiling ...
[:viewer] Build failure:
------ ERROR -------------------------------------------------------------------
 File: /Users/amantini/dev/clerk/src/nextjournal/clerk/sci_env.cljs:53:10
--------------------------------------------------------------------------------
  50 |   (sci/new-var 'doc-url (fn [x] (str "#" x))))
  51 | 
  52 | (def viewer-namespace
  53 |   (merge (sci/copy-ns nextjournal.clerk.viewer (sci/create-ns 'nextjournal.clerk.viewer))
----------------^---------------------------------------------------------------
Encountered error when macroexpanding sci.core/copy-ns.
IllegalStateException: Attempting to call unbound fn: #'sci.impl.cljs/cljs-ns-publics
	clojure.lang.Var$Unbound.throwArity (Var.java:45)
	sci.core/copy-ns (core.cljc:411)
	sci.core/copy-ns (core.cljc:364)
	clojure.core/apply (core.clj:671)
	clojure.core/apply (core.clj:662)
	cljs.analyzer/macroexpand-1*/fn--3704 (analyzer.cljc:4025)
	cljs.analyzer/macroexpand-1* (analyzer.cljc:4023)
	cljs.analyzer/macroexpand-1* (analyzer.cljc:4010)
	cljs.analyzer/macroexpand-1 (analyzer.cljc:4074)
	cljs.analyzer/macroexpand-1 (analyzer.cljc:4070)

```
which I don't get on `main`

**Comment by zampino** [comment]
`bb dev` works after removing `.shadow-cljs`.

**Pull request merged**
