### PR TITLE
Fix viewer regressions for formulas and quotes

### PR DESCRIPTION
**Pull request by zampino**
* Restores correct display of block formulas in markdown parts
* Formulas displayed with `clerk/tex` are rendered in display mode now
* Removes extra `"` added by tailwind on blockquotes

### CODE REVIEW

**Comment by zampino** [comment]
This change introduces a scrollable overflow on markdown blocks which contain formulas. @joe-loco do you have an idea what's going on here https://snapshots.nextjournal.com/clerk/build/8833c19119905e53367b2d19d83f17912fbd280a/index.html#/notebooks/viewers/tex.clj?

**Comment by joe-loco** [comment]
@zampino Fixed the inline formula scrolling and disabled auto-quoting blockquotes.

**Comment by zampino** [comment]
Can we merge this? Maybe excluding 6e2f40f if it conflicts with https://github.com/nextjournal/clerk/pull/140?

**Comment by joe-loco** [comment]
@zampino Fine to merge! No need to exclude https://github.com/nextjournal/clerk/commit/6e2f40f68ff92a3680d47016a137c421f61f3a06. #140 is entirely experimental at this point.

**Pull request merged**
